// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'HobbyName': string;
  'HobbyPassion': string;
  'HobbyWrapper': string;
  'HobbyYear': string;
}
declare var cssExports: CssExports;
export = cssExports;
