// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'ButtonDeleteHobby': string;
  'Hobby': string;
  'HobbyName': string;
  'HobbyPassion': string;
  'HobbyWrapper': string;
  'HobbyYear': string;
  'TextInput': string;
}
declare var cssExports: CssExports;
export = cssExports;
