// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'ContentWrapper': string;
  'Header': string;
  'MainContainer': string;
  'MainContent': string;
}
declare var cssExports: CssExports;
export = cssExports;
