// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SelectedUser': string;
  'User': string;
}
declare var cssExports: CssExports;
export = cssExports;
